title: "TapAudio"

toc_levels: 2..4

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true  # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Google Analytics
#google_analytics:           # Format: UA-xxxxxx-xx
# ga_domain: 

#plugin
plugins:
  - jekyll-feed